# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # secret_key is dynamically overridden by the SEARXNG_SECRET environment variable in docker-compose
  limiter: true
  image_proxy: true
search:
  formats:
#    - html
#    - csv
    - json
#    - rss
ui:
  static_use_hash: true
